name: My Workflow
on: 
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Run the action
        uses: ankitrai1985/custom-github-action@v4
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
