name: My Workflow1
on: 
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Install dependencies ci
        run: npm ci

      - name: Checkout action code
        uses: actions/checkout@v2
        with:
          repository: ankitrai1985/custom-github-action
          ref: v3
          path: ./custom-github-action

      - name: Install action dependencies
        run: npm ci
        working-directory: ./custom-github-action

      - name: Run the action
        uses: ./custom-github-action
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
