name: Event Trigger Example

on:
  workflow_dispatch
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  check_event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Name
        run: echo "The event name is ${{ github.event_name }}"
