name: Event Trigger Example

on: workflow_dispatch

jobs:
  check_event:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Name
        run: echo "The event name is ${{ github.event_name }}"
