name: Install Dependencies

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute install_dependencies.sh script
        run: |
          chmod +x install_dependencies.sh
          ./install_dependencies.sh
