name: labled

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ${{ github.event.label.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"
