name: Print Environment Variables

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use (dev or prod)' 
        required: true

jobs:
  print-vars:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variables
        run: |
          echo "MY_CURRENT_ENV : ${{ env.MY_CURRENT_ENV }}"
