name: Publish to GitHub Packages

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # You can specify your desired Java version here

      - name: Build and publish package
        run: |
          # Your commands to build and publish the package
          ./gradlew clean build publishToMavenLocal

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-package
          path: build/libs/
