name: Echo Name Workflow
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  echo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Echo name
        run: echo "Hello, ${{ inputs.name }}"
