name: Reusable workflow
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  echo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Echo name
        run: echo "Hello, ${{ inputs.name }}"
