name: Consume Build with Gradle Template

on:
  workflow_dispatch

jobs:
  consume_build_template:
    runs-on: ubuntu-latest

    steps:
      - name: Run Build with Gradle template
        uses: ./.github/workflows/build-templated.yml
