name: Consume Build with Gradle Template

on:
  workflow_dispatch

jobs:
  consume_build_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Build with Gradle template
        run: ./.github/workflows/build-templated.yml
